### ISSUE TITLE
ustat deprecated on Linuxes after e.g. Ubuntu 18.04

### ISSUE THREAD

**Issue by PHSchmidt8008** [arnoldrobbins/s4-3b1-pc7300#1]
Latest glibc has deprecated ustat in favor of fstatfs and fstat it seems. An update so will build on latest would be greatly appreciated!

**Comment by arnoldrobbins** [comment]
I have changed the code to use statfs.

It should compile for you now.  NOTE that this change probably breaks the intended functionality of being able to test that the "device" being checked (or file system image, in our case) is not mounted.

I think I know how to actually write the code that would do the checking correctly, but it's 1/2 to 1 hours' work. I will try to do it over the next week or so.  For now I will leave the issue open.  Thanks.

**Comment by arnoldrobbins** [comment]
I have now fixed this correctly.  s4fsck won't check a file system image if it's mounted. Closing the issue.
