### ISSUE TITLE
s4export fails with "badmagic" but s4disk appears to find it OK

### ISSUE THREAD

**Issue by PHSchmidt8008** [arnoldrobbins/s4-3b1-pc7300#2]
On:  Linux raspberrypi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux

pi@raspberrypi:~/s4-3b1-pc7300 $ s4export -i hd.img -o hd.fs
Volume file:   hd.img
FS-image file: hd.fs
Checksumming 782
BBT CHKSUM ffff
FS is on partition 2
RAW DISK BLOCK:
 Dec Hex  0 1 2 3 4 5 6 7  8 9 a b c d e f  0 1 2 3 4 5 6 7  8 9 a b c d e f    123456789abcdef 123456789abcdef
   0 000 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
  32 020 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
  64 040 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
  96 060 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 128 080 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 160 0a0 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 192 0c0 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 224 0e0 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 256 100 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 288 120 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 320 140 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 352 160 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 384 180 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 416 1a0 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 448 1c0 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 480 1e0 0000000000000000 0000000000000000 0000000000000000 0000000000000000   ................................
 512 200 46000000ffffff6f 0200000008300100 083001003c120000 0400000000000000   F......o.....0...0..<...........
 544 220 0200000002000000 53000000fdffff6f 0200000044420100 4442010050030000   ........S......o....DB..DB..P...
 576 240 0500000018000000 0400000000000000 62000000feffff6f 0200000094450100   ................b......o.....E..
 608 260 9445010030000000 0500000001000000 0400000000000000 7100000009000000   .E..0...................q.......
 640 280 02000000c4450100 c445010088290000 0400000000000000 0400000008000000   .....E...E...)..................
 672 2a0 7a00000009000000 420000004c6f0100 4c6f010060000000 040000001c000000   z.......B...Lo..Lo..`...........
 704 2c0 0400000008000000 7e00000001000000 06000000ac6f0100 ac6f0100a4000000   ........~............o...o......
 736 2e0 0000000000000000 0400000004000000 8300000001000000 0600000050700100   ............................Pp..
 768 300 5070010064221000 0000000000000000 1000000000000000 8900000001000000   Pp..d"..........................
 800 320 06000000b4921100 b4921100800e0000 0000000000000000 0400000000000000   ................................
 832 340 9b00000001000000 0200000038a11100 38a11100e9830100 0000000000000000   ............8...8...............
 864 360 0800000000000000 a300000001000000 0200000024251300 2425130019000000   ....................$%..$%......
 896 380 0000000000000000 0400000000000000 ab00000001000000 0200000040251300   ............................@%..
 928 3a0 4025130020090000 0000000000000000 0400000000000000 b600000001000070   @%.. ..........................p
 960 3c0 82000000602e1300 602e130048160000 0c00000000000000 0400000000000000   ....`...`...H...................
 992 3e0 c100000001000000 02000000a8441300 a844130004000000 0000000000000000   .............D...D..............
FS Superblock is badmagic
Can't find filesystem in 'hd.img'  -- badmagic

pi@raspberrypi:~/s4-3b1-pc7300 $ s4disk -s hd.img 
Device file hd.img
Checksumming 782
BBT CHKSUM ffff
Showing disk header from 'hd.img'
Magic 55515651 is 55515651, checksum 60c4f42 (unchecked) SWAPPED
 1024 cyls, 8 heads; 17 s/trk, 136 s/cyl; step 0, 512 byte sectors
 139264 blocks, 69632k bytes 68M bytes
Name 'WINCHE'  flags 0x8  SD  SAME  PRECOMP  NEWTAB 
Loader is 46 blocks at PBA 4
Bad Block Table is 2 blocks at PBA 2

Partitions: (3)
Num  STrk  Ntrk  PBA   LBA  Cyl     Offset   PSects      PSize        LSects      LSize
---  ----  ---- ----- ----- ----  ---------  ------- ---------------  ------- ---------------
  0     0     8     0     0    0          0      136     68k   0.07M      128     64k   0.06M
  1     8   625   136   128    1      69632    10625   5312k   5.19M    10000   5000k   4.88M
  2   633  7559 10761 10128   79    5509632   128503  64251k  62.75M   120944  60472k  59.05M

Special sections in part 0
  Resmap:
  [0] at FSBLK 2, blocks 23
  [1] at FSBLK 1, blocks 1

Bad block mapping is turned OFF

**Comment by arnoldrobbins** [comment]
Hi. I think this is fixed in the current code. Please recheck. Closing the issue in the meantime.
